services:

  jenkins:
    build: ./jenkins
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root
    environment:
      - JENKINS_ADMIN_PASSWORD=admin
    networks:
      - cicd_network


volumes:
  jenkins_home:
    external: true

networks:
  cicd_network:
    driver: bridge
